- arguments: [-XCPP, --cpp-define=HLINT, --cpp-ansi]

- ignore:
    name: Use camelCase

- ignore:
    name: Use lambda-case

- ignore:
    name: Use || # We define a different `or`

- ignore:
    name: Use && # We define a different `and`

- ignore: {name: Hoist not, within: [Ersatz.Bit]} # This is how we define `any`, ya dingus
- ignore: {name: Use infix, within: [Ersatz.Relation.Op]} # We define a different `union` function in this module
